language: elixir
cache:
  directories:
    - deps
    - _build
services:
  - docker
  - postgresql
addons:
  postgresql: "9.6"
elixir:
  - 1.6.3
otp_release:
  - 20.2
addons:
  apt:
    packages:
      - docker-ce
notifications:
  slack:
    rooms:
      - secure: "bt5f6r5kl4XmmIeRN2JwB2N17QWz1Uj+KAOfW3UT7+r4+U7ggWFix+HuuZNJBjVzsvvHrPn/4L7uCLOSuSrBqt2mhPxJ3QGO/xVVCLI2luUawPFlm2AVRfRVvCUb9nx+YWpMSDAR1Qkzjl20mx3BxHeW54fnDw13lCV4EAzvsYVkA94HU6bDk9BWXolVrUggx26OdQ6TdzE3Y5ce841//q1VuzaFmlf9K9FWKFf7OlWPuToWNZj5PfiWNLiwMOYnTrt0shpNMT8HkdPKDHLFS1h8RHuimoOb3CLGyBWehgEK6tlAP7O9RZ5ECeezHbmsIAeZgZVQqhU/t2mSzGS9rRidl2hTeVcXW6EzLWZqi0VhUljjq2CFe3ZmWH3/Ql65hmvpJxPlsz3VhcELV6JGZGe9vpuqmK8KZWVqwj5H1MOwO6Kr29vnli6KwXGcDUGAvbMyWrjySWpmWs7AYrjCG7v5PVfy7vYPneLjuP/tgIivgsZFXRwANaozjVo03Dp17Yz/UpZ6DymwYtn7ZpjfHqLAFxw2ZN3azQXCD6N9jvehjIOInY+V+gYEqoI/M8H1qCu+Bd+nfSqR7doX7Pt+fQf/+gFy3dBWQTAOu4GwEkZEBlEhXAmLiWK5r2G5rxtm2XCgs3W/RnE4vYyCW8XHDPfKebtS92+pLrWahsBxhv4="
    on_success: always
env:
  global:
    - CHART=mithril
    - MIX_ENV=test
    - REQUIRE_VERSION_TAGS="true"
    - DOCKER_HUB_ACCOUNT=edenlabllc
    - TRUNK_BRANCH="develop"
    # Docker and GitHub credentials
    - secure: "XnqLhIZf2P2iw5QwbS+0RDmDPTUoRNe6TucJmjiRD6fKw6wkT5QWD1/3hVS6sDidnFGeg9DsXypYMUqXjnfP2KG2aiqgK558e00h/5DpcL9XYnxyU3YBZBB6WCu+aGgIxkdtnwOF/WGQgv1NkCgC51H7Cq235HuUX6PkvuYGEe7Cy/6kzOMr7+Qrmd6ywPKPRidW88zMneKJjIV8sMsNXhdxdkq4logneiaaseJQ0pysUMKmKMTxoefngKT5XL59KWznsMOXoEcb08XIPp6BqtPIay0CrGGnX9ZsQqBVWRfwBEDV7QS/U1Ga0cYtO80xVLT0mtWk4NyGs9WRB4KaR7LyWI0ZTD785pQdujisJ6lRwDOkrLB8hcrBWGhSINKYgdYTIPk4I5eYAjpgFYAqVAAs7wYdszkLP5HjjXdJtAKpNZT1MwT/t4HZr03Ia7H9yKmgzGciPWqE1ODVW3US7Q5oVfrONXzvcTS3goNpHx6qup0Q9ROoeRkhAss2nuqwwCRljYZzWergSdiS874sgKgym/IclbiL6hKu4iZ33gZQcRACGEnJWx1vW/p8waiF1c3xa7u6QAqDVawO73XRZffAlI+HOK66M9++QiXly0Mp2ioXVTGK08cl0LE9/3P5+mkTmYQyabHtOH1smxfvsaBjtnnOxhDj+OyYySllHh0="
    - secure: "GYerLjERdMwmKNYa2HVRUs5690dbfaCekLfLJHn+AsqFdFAZ7NLEi+Y2f3Vl+IT1ukS8Gp5GWWsmqCQ0YBQAgEp0+lbZuWMDJ6zJ7NZosYgxVf348+DWFjuZ6MaDZOOSDxzM3TQCcBty4jgYlElmRXZD6A7geytiPcg3nmPQ67+ng6oEvAbm5aFyIZM9XTl+N1CO0kKRvgUa9iFyW6TNzU+CLYclPEDW+iBBwrjtugDAiGRySCOdISI410hgOoO2t2e/QNP0r0PciSM1E8txiKPEhCp/a9pj/ZsoeaQUd7rVBW0bU8vRb4FuGmA14cE2dUo9Y23OoEB9gTIVuLFIA9la12HigCQBZTXC0ChZkHcy5wo+e/5psBY8se+P29l8WSFIpNBjlfDeM72zkvzyzk6pu/3wD0vtJx7sVJvSUFfeLTIFvOjBpvjy5Pamf4Q/NUGxOe3w9F/2ed2A3onMn3nkkpA27PepYs3frQImt8Nf7lqHYeySaQLbqXnEWttIJW8tb945wHqBPYcg5FfXWyCwb34b4N7nh8PswdW8KvZ7+KIJZ+WjT/89zJS1nWnqTW+WpsqycgJWGIV0qLnrj/sm8Fg0ncgmak3WIrObr949Nna8CR5vdsCQI727quh7yVc5wfqFwHjfi6zl7FuM4ea4UzfOen0I7UHkSk+81x0="
branches:
  # Releases are generated automatically, stop infinite build loop
  except:
    - /[0-9]*\.[0-9]*\.[0-9]*/
before_install:
  - openssl aes-256-cbc -K $encrypted_792e32fefb8e_key -iv $encrypted_792e32fefb8e_iv -in eHealth-8110bd102a69.json.enc -out eHealth-8110bd102a69.json -d
  # Expose MQ and DB to Docker container
  - sudo ./bin/ci/init-db.sh
before_script:
  # Extract project name and version from mix.exs
  - source ./bin/ci/release/fetch-project-environment.sh
  # Load information about new version
  - source ./bin/ci/release/fetch-source-version.sh
  # Load information about changelog
  - source ./bin/ci/release/fetch-changelog.sh
script:
  # Check for versioning error
  - ./bin/ci/release/check-version-error.sh || travis_terminate 1
  # Increment version in mix.exs
  - ./bin/ci/release/put-source-version.sh || travis_terminate 1
  # Create release notes log for minor version
  - ./bin/ci/release/put-release-notes.sh
  # Run all tests except pending ones
  - ./bin/mix_tests.sh || travis_terminate 1
  # Build Docker container
  - ./bin/ci/release/build-container.sh || travis_terminate 1
  # Initialize DB for Docker container
  - MIX_ENV=dev mix ecto.setup
  # Run Docker container
  - sudo ./bin/ci/release/start-container.sh
  - sudo ./bin/ci/release/check-container.sh || travis_terminate 1
  # Submit Docker container to Docker Hub and create GitHub Release by pushing tag with changelog
  - ./bin/ci/release/push-changes.sh || travis_terminate 1
  # CD to Dev
  - sudo ./bin/deploy.sh || travis_terminate 1
